[package]
name = "toy-regex"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.30", features = ["derive"] }
automaton = { path = "./automaton" }

[workspace]
members = ["automaton", "parser"]

[workspace.dependencies]
anyhow = "1.0.95"
parser = { path = "parser" }
